name: FloatingText
main: floatingtext.Main
author: maru
version: "1.0.0"
api: ["1.0.0"]

commands:
 makeft:
  usage: /makeft <text>
  description: "Make floating text."
  permission: floatingtext.commands.makeft

permissions:
 floatingtext.*:
  default: OP
  children:
   floatingtext.commands.*:
    default: OP
    children:
     floatingtext.commands.makeft:
      default: OP
   floatingtext.remove:
    default: OP